#import <Foundation/Foundation.h>
@interface PodsDummy_Pods_Assignment_4___Instagram_Assignment_4___InstagramUITests : NSObject
@end
@implementation PodsDummy_Pods_Assignment_4___Instagram_Assignment_4___InstagramUITests
@end
